Imported Debian patch 2.5.1-1

diff --git a/changer-src/chg-disk.sh.in b/changer-src/chg-disk.sh.in
--- a/changer-src/chg-disk.sh.in
+++ b/changer-src/chg-disk.sh.in
@@ -1,4 +1,4 @@
-#! /bin/sh
+#! @SHELL@
 #
 # Amanda, The Advanced Maryland Automatic Network Disk Archiver
 # Copyright (c) 1991-1999 University of Maryland at College Park
@@ -86,25 +86,36 @@ isinteger() {
 	expr "$1" : '[0-9][0-9]*$' > /dev/null 2>&1
 }
 
+# Need rwx access to the virtual tape itself.
+if ! test -d $SLOTDIR; then
+    echo "Virtual-tape directory $SLOTDIR does not exist." 1>&2
+    exit 2
+fi
+if ! test -w $SLOTDIR; then
+    echo "Virtual-tape directory $SLOTDIR is not writable." 1>&2
+    exit 2
+fi
+
+
 # need rwx access to directory of changer file
 CHANGERFILE=`amgetconf$SUF changerfile`
 CFDir=`dirname ${CHANGERFILE}`
 [ -d ${CFDir} -a -r ${CFDir} -a -w ${CFDir} -a -x ${CFDir} ] ||
-	{ echo "$MYNAME: need 'rwx' access to '$CFDir'" ; exit 2 ; }
+	{ echo "$MYNAME: need 'rwx' access to '$CFDir'" 1>&2 ; exit 2 ; }
 
 # check or create changer metadata files
 ACCESSFILE=$CHANGERFILE-access
 [ -f $ACCESSFILE -a -r $ACCESSFILE -a -w $ACCESSFILE ] ||
 	echo 0 > $ACCESSFILE ||
-	{ echo "$MYNAME: could not access or create '$ACCESSFILE'" ; exit 2 ; }
+	{ echo "$MYNAME: could not access or create '$ACCESSFILE'" 1>&2 ; exit 2 ; }
 CLEANFILE=$CHANGERFILE-clean
 [ -f $CLEANFILE -a -r $CLEANFILE -a -w $CLEANFILE ] ||
 	echo 0 > $CLEANFILE ||
-	{ echo "$MYNAME: could not access or create '$CLEANFILE'" ; exit 2 ; }
+	{ echo "$MYNAME: could not access or create '$CLEANFILE'" 1>&2 ; exit 2 ; }
 SLOTFILE=$CHANGERFILE-slot
 [ -f $SLOTFILE -a -r $SLOTFILE -a -w $SLOTFILE ] ||
 	echo 0 > $SLOTFILE ||
-	{ echo "$MYNAME: could not access or create '$SLOTFILE'" ; exit 2 ; }
+	{ echo "$MYNAME: could not access or create '$SLOTFILE'" 1>&2 ; exit 2 ; }
 
 # read and check metadata
 ACCESSCOUNT=`cat $ACCESSFILE`
@@ -116,6 +127,7 @@ FIRSTSLOT=1
 LASTSLOT=`amgetconf$SUF tapecycle`
 CURSLOT=0
 CLEANSLOT=$LASTSLOT
+NSLOT=`expr $LASTSLOT - $FIRSTSLOT + 1`
 
 load() {
   WHICHSLOT=$1;
@@ -165,13 +177,13 @@ loadslot() {
     if [ $WHICHSLOT -ge $FIRSTSLOT -a $WHICHSLOT -le $LASTSLOT ]; then
       NEWSLOT=$WHICHSLOT
     else
-      echo "0 illegal request"
+      echo "$WHICHSLOT illegal slot"
       exit 1
     fi
   elif [ $WHICHSLOT = "clean" ]; then
     NEWSLOT=$CLEANSLOT
   else
-    echo "0 illegal request"
+    echo "$WHICHSLOT illegal request"
     exit 1
   fi
   if [ $NEWSLOT = $CURSLOT ]; then
@@ -204,7 +216,7 @@ loadslot() {
 
 info() {
   readstatus
-  echo "$CURSLOT $LASTSLOT $FIRSTSLOT"
+  echo "$CURSLOT $NSLOT 1"
   exit 0
 }
 
diff --git a/server-src/amdump.sh.in b/server-src/amdump.sh.in
--- a/server-src/amdump.sh.in
+++ b/server-src/amdump.sh.in
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!@SHELL@
 #
 # Amanda, The Advanced Maryland Automatic Network Disk Archiver
 # Copyright (c) 1991-1998 University of Maryland at College Park
@@ -47,20 +47,28 @@ else
 	SUF=
 fi
 
+if [ $# -lt 1 ]
+then
+        echo "Usage: amdump config [host [disk...]...]" 1>&2
+        exit 1
+fi
+
+
 conf=$1
 if [ ! -d $confdir/$conf ]; then
-    echo "amdump$SUF: could not find directory $confdir/$conf"
+    echo "amdump$SUF: could not find directory $confdir/$conf" 1>&2
     exit 1
 fi
+shift
 
 cd $confdir/$conf || exit 1
 
-logdir=`amgetconf$SUF $conf logdir`
+logdir=`amgetconf$SUF $conf logdir "$@"`
 [ $? -ne 0 ]  && exit 1
 errfile=$logdir/amdump
-tapecycle=`amgetconf$SUF $conf tapecycle`
+tapecycle=`amgetconf$SUF $conf tapecycle "$@"`
 [ $? -ne 0 ]  && exit 1
-dumpuser=`amgetconf$SUF $conf dumpuser`
+dumpuser=`amgetconf$SUF $conf dumpuser "$@"`
 [ $? -ne 0 ]  && exit 1
 
 runuser=`{ whoami ; } 2>/dev/null`
@@ -73,20 +81,20 @@ if [ $? -ne 0 ]; then
 	fi
 fi
 
-if [ $runuser != $dumpuser ]; then
-	echo "amdump: must be run as user $dumpuser, not $runuser"
-	exit 1
-fi
+#if [ $runuser != $dumpuser ]; then
+#	echo "amdump: must be run as user $dumpuser, not $runuser" 1>&2
+#	exit 1
+#fi
 
 if test -f hold; then
-	echo "amdump: waiting for hold file to be removed" >&2
+	echo "amdump: waiting for hold file to be removed" 1>&2
 	while test -f hold; do
 		sleep 60
 	done
 fi
 
 if test -f $errfile || test -f $logdir/log; then
-	echo "amdump: amdump or amflush is already running, or you must run amcleanup" >&2
+	echo "amdump: amdump or amflush is already running, or you must run amcleanup" 1>&2
 	exit 1
 fi
 
@@ -98,20 +106,20 @@ touch $errfile
 exec </dev/null 2>>$errfile 1>&2
 echo "amdump: start at `date`"
 echo "amdump: datestamp `date +%Y%m%d`"
-$libexecdir/planner$SUF "$@" | $libexecdir/driver$SUF $conf
+$libexecdir/planner$SUF $conf "$@" | $libexecdir/driver$SUF $conf "$@"
 echo "amdump: end at `date`"
 
 # Send out a report on the dumps.
-$sbindir/amreport$SUF $conf
+$sbindir/amreport$SUF $conf "$@"
 
 # Roll the log file to its datestamped name.
-$libexecdir/amlogroll$SUF $conf
+$libexecdir/amlogroll$SUF $conf "$@"
 
 # Trim the log file to those for dumps that still exist.
-$libexecdir/amtrmlog$SUF $conf
+$libexecdir/amtrmlog$SUF $conf "$@"
 
 # Trim the index file to those for dumps that still exist.
-$libexecdir/amtrmidx$SUF $conf
+$libexecdir/amtrmidx$SUF $conf "$@"
 
 # Keep a debug log through the tapecycle plus a couple of days.
 maxdays=`expr $tapecycle + 2`
