Imported Upstream version 2.6.0

diff --git a/autogen b/autogen
--- a/autogen
+++ b/autogen
@@ -1,19 +1,46 @@
 #! /bin/sh
-# rebuilds files generated by autoconf&automake.
-# autoconf 2.13 and automake 1.4 or newer are required
-# arguments are forwarded to the autoreconf script.
 
+# cd to the directory we're run from
 cd `dirname $0`
 
+# if you change this, please also change it in the root Makefile.am
+includes="-I . -I config -I config/gettext-macros -I config/gnulib -I config/amanda -I config/macro-archive"
+
+# clean up
+rm -f aclocal.m4
+rm -rf autom4te*.cache
+rm -f configure
+
+die() {
+    echo x"${@}" | sed s/^x//
+    exit 1
+}
+
+echo "See DEVELOPING for instructions on updating:"
+echo " * gettext macros"
+echo " * gnulib"
+echo " * libtool files"
+
+echo "..creating file lists"
+(   cd config
+    for m4dir in amanda gettext-macros gnulib macro-archive; do
+	echo "## this file is automatically generated by autogen" > "$m4dir/file-list"
+	for f in $m4dir/*.m4; do echo "EXTRA_DIST += $f" >> "$m4dir/file-list"; done
+    done
+
+    echo "## this file is automatically generated by autogen" > "automake/file-list"
+    for f in automake/*.am; do echo "EXTRA_DIST += $f" >> "automake/file-list"; done
+)
+
+echo "..aclocal"
+aclocal $includes || die "aclocal failed"
+
+echo "..autoconf"
+autoconf || die "autoconf failed"
+
+echo "..autoheader"
+autoheader || die "autoheader failed"
 touch config/config.h.in
 
-if test x`ls -1t acinclude.m4 2>/dev/null \
-	    config/gnulib.m4i config/acinclude.m4i config/libtool.m4i |
-	  sed 1q` != x"acinclude.m4"; then
-    rm -f acinclude.m4
-    # keep libtool.m4i first here, as it has a "serial number" comment that it wants
-    # first in the file
-    cat config/libtool.m4i config/gnulib.m4i config/acinclude.m4i > acinclude.m4
-fi
-
-autoreconf --warning=syntax --warning=no-portability --force ${1+"$@"} || exit 1
+echo "..automake"
+automake --force --copy --warnings=none || die "automake failed"
diff --git a/changer-src/chg-lib.sh.in b/changer-src/chg-lib.sh.in
--- a/changer-src/chg-lib.sh.in
+++ b/changer-src/chg-lib.sh.in
@@ -17,53 +17,116 @@ MTF=@MT_FILE_FLAG@
 # No user-level customization should be required beyond this point.
 ################################################################################
 
-####
-# Set up paths, including PATH for finding amanda executables
-
-PATH="$PATH:@sbindir@:@libexecdir@"
 prefix="@prefix@"
 exec_prefix="@exec_prefix@"
 sbindir="@sbindir@"
 libexecdir="@libexecdir@"
-
-####
-# Gettext
-
-#+
-# Function to:
-#    Simplify gettext usage by allowing printf format
-#    strings for translators, use _() identifier for
-#    xgettext extraction similar to "C" usage and
-#    collapsing "printf `gettext fmt` ...", which is
-#    used everywhere, into one function.
-#-
-_() {
-	fmt=`gettext -d amanda "$1"`
-	shift
-	printf "$fmt" $*
-}
+amlibexecdir="@amlibexecdir@"
+. "${amlibexecdir}/amanda-sh-lib.sh"
 
 ####
 # Eponymous functions to access various amanda apps
+# TODO: move to amanda-sh-lib.sh
 
 if test "@USE_VERSION_SUFFIXES@" = "yes"; then
     amgetconf() {
         "${sbindir}/amgetconf-@VERSION@" "${@}"
     }
-    ammt() {
-        "${sbindir}/ammt-@VERSION@" "${@}"
-    }
-    amdd() {
-        "${sbindir}/amdd-@VERSION@" "${@}"
+    amdevcheck() {
+        "${sbindir}/amdevcheck-@VERSION@" "${@}"
     }
 else
     amgetconf() {
         "${sbindir}/amgetconf" "${@}"
     }
-    amdd() {
-        "${sbindir}/amdd" "${@}"
-    }
-    amdd() {
-        "${sbindir}/amdd" "${@}"
+    amdevcheck() {
+        "${sbindir}/amdevcheck" "${@}"
     }
 fi
+
+# This function tries to find a useable mt binary. If a fully-qualified path
+# was provided at configure time or via a config file, we check that it
+# exists and is executable. If an incomplete path was specified (e.g., "mt"),
+# we ask the shell to search the path. Returns 0 on success, 1 on failure.
+
+try_find_mt() {
+    # Only do this once.
+    if test -n $mt_found; then
+        return 0
+    fi
+
+    if test -z $MT; then
+        MT=mt
+    fi
+
+    if "`echo $MT | dd bs=1 count=1`" = "/"; then
+        if ! test -f "${MT}"; then
+            echo `_ "mt binary at '%s' not found" "$MTX"`
+            return 1
+        fi
+        if ! test -x "${MT}"; then
+            echo `_ "mt binary at '%s' is not executable" "$MTX"`
+            return 1
+        fi
+    else
+        # try running it to see if the shell can find it
+        "$MT" >/dev/null 2>/dev/null
+        if test $? -eq 127 -o $? -eq 126; then
+            echo `_ "Could not run mt binary at '%s'" "$MTX"`
+            return 1
+        fi
+    fi
+
+    mt_found=yes
+    return 0
+}
+
+# This function strips the tape: from the front of device names.
+# Capture its output with ``.
+tape_device_filename() {
+    # Easy (?) to express this in Perl.
+    perl -e '$ARGV[0] =~ /^(?:([^:]+):)?(.*)$/;
+             print $2 if ($1 || "tape") eq "tape"' "$1"
+}
+
+# Runs amdevcheck to find out if a particular device is usable. Finds the
+# config name based on pwd, so run it from the config directory. The sole
+# argument should be the device name to check. Note that amdevcheck can FP
+# on device status, since some devices can't differentiate between device
+# problems and an unlabeled volume.
+amdevcheck_status() {
+    amdevcheck_config_dir=`pwd`
+    amdevcheck_config_name=`basename $amdevcheck_config_dir`
+    amdevcheck_output=`amdevcheck $amdevcheck_config_name $@`
+
+    if test $? -eq 0 || \
+        echo $amdevcheck_output | grep UNLABELED > /dev/null; then
+        return 0
+    else
+        return 1
+    fi
+}
+
+# This attempts to eject a device using whatever system tools are available.
+# At the moment, that means mt for tapes, and nothing otherwise, but might
+# be extended at some later time.
+
+try_eject_device() {
+    if echo "$1" | grep -e '^tape:' > /dev/null; then
+        try_eject_device_tape="`echo \"$1\" | cut -b6-`"
+    elif echo "$1" | grep -v : > /dev/null; then
+        try_eject_device_tape="$1"
+    else
+        try_eject_device_tape=
+    fi
+
+    if test -n "$try_eject_device_tape"; then
+        if try_find_mt; then
+            $MT $MTF "$try_eject_device_tape" eject
+        fi
+    else
+        # Technically we failed to eject the device, but we presume that's
+        # because it doesn't require ejection.
+        return 0
+    fi
+}
diff --git a/man/Makefile.am b/man/Makefile.am
--- a/man/Makefile.am
+++ b/man/Makefile.am
@@ -2,21 +2,19 @@
 
 transform =	s,x,x,;
 
-if WANT_AMPLOT
-AMPLOT_MAN8_PAGES = amplot.8
-endif
+AMPLOT_MAN_PAGES =  amplot.8
 
-COMMON_MAN8_PAGES = amanda.8
-
-COMMON_MAN5_PAGES = amanda.conf.5 \
+COMMON_MAN_PAGES =  amanda.8 \
+		    amanda.conf.5 \
 		    amanda-client.conf.5
 
-#if WANT_SERVER
-SERVER_MAN8_PAGES = amadmin.8 \
+SERVER_MAN_PAGES =  amadmin.8 \
 		    amcheck.8 \
 		    amcheckdb.8 \
+		    amcheckdump.8 \
 		    amcleanup.8 \
 		    amdd.8 \
+		    amdevcheck.8 \
 		    amdump.8 \
 		    amflush.8 \
 		    amgetconf.8 \
@@ -31,39 +29,41 @@ SERVER_MAN8_PAGES = amadmin.8 \
 		    amtoc.8 \
 		    amverify.8 \
 		    amverifyrun.8 \
-		    amfetchdump.8 \
+		    amserverconfig.8 \
+		    amaddclient.8 \
+		    amcheckdump.8 \
 		    amcrypt.8 \
 		    amaespipe.8 \
+		    amgpgcrypt.8 \
+		    amcryptsimple.8  \
 		    amcrypt-ossl.8 \
 		    amcrypt-ossl-asym.8
-#endif
 
+RECOVER_MAN_PAGES =  amrecover.8
+
+RESTORE_MAN_PAGES =  amrestore.8 \
+		     amfetchdump.8
+
+ALL_MAN_PAGES = $(AMPLOT_MAN_PAGES) \
+	   $(COMMON_MAN_PAGES) \
+	   $(COMMON_MAN_PAGES) \
+	   $(SERVER_MAN_PAGES) \
+	   $(RECOVER_MAN_PAGES) \
+	   $(RESTORE_MAN_PAGES)
+
+WANTED_MAN_PAGES = $(COMMON_MAN_PAGES)
+if WANT_AMPLOT
+  WANTED_MAN_PAGES += $(AMPLOT_MAN_PAGES)
+endif
+if WANT_SERVER
+  WANTED_MAN_PAGES += $(SERVER_MAN_PAGES)
+endif
 if WANT_RECOVER
-RECOVER_MAN8_PAGES = amrecover.8
+  WANTED_MAN_PAGES += $(RECOVER_MAN_PAGES)
 endif
-
 if WANT_RESTORE
-RESTORE_MAN8_PAGES = amrestore.8
+  WANTED_MAN_PAGES += $(RESTORE_MAN_PAGES)
 endif
-
-man8_pages = $(COMMON_MAN8_PAGES) \
-	    $(AMPLOT_MAN8_PAGES) \
-	    $(SERVER_MAN8_PAGES) \
-	    $(RECOVER_MAN8_PAGES) \
-	    $(RESTORE_MAN8_PAGES)
-
-man5_pages = $(COMMON_MAN5_PAGES)
-
-ALL_MAN_PAGES = $(AMPLOT_MAN8_PAGES) \
-	   $(COMMON_MAN5_PAGES) \
-	   $(COMMON_MAN8_PAGES) \
-	   $(SERVER_MAN8_PAGES) \
-	   $(RECOVER_MAN8_PAGES) \
-	   $(RESTORE_MAN8_PAGES)
-
-# These lines are needed to force automake to set the $man<n>dir variables.
-man5_MANS =
-man8_MANS =
 
 SRCMANPAGEDIR  = $(srcdir)/xml-source
 
@@ -87,64 +87,23 @@ xml-source/%.proc.xml: $(SRCMANPAGEDIR)/%.xml $(srcdir)/xslt/expand-sambadoc.xsl
 	$(XSLTPROC) $(XSLTPROC_FLAGS) --path $(srcdir)/xslt/ --xinclude --stringparam latex.imagebasedir "$*/" --stringparam noreference 1 --output $@ $(srcdir)/xslt/expand-sambadoc.xsl $<
 
 %: xml-source/%.proc.xml $(srcdir)/xslt/man.xsl
-	$(XSLTPROC) $(XSLTPROC_FLAGS) --path $(srcdir)/xslt/ --output $@ http://docbook.sourceforge.net/release/xsl/1.72.0/manpages/docbook.xsl $<
+	$(XSLTPROC) $(XSLTPROC_FLAGS) --path $(srcdir)/xslt/ --output $@ http://docbook.sourceforge.net/release/xsl/$(XSLREL)/manpages/docbook.xsl $<
 
 else	!ENABLE_MANPAGE_BUILD
 
 %: $(SRCMANPAGEDIR)/%.xml
 	@echo WARNING: Not building needed $@ because building manpages is disabled.
+	@echo 'DUMMY' > $@
+
 endif
 
-all: $(ALL_MAN_PAGES)
+# double-check that we don't ship dummy manpages
+dist-hook:
+	for f in $(WANTED_MAN_PAGES); do \
+		if sed -e 1q $(distdir)/$$f | $(GREP) '^DUMMY$$' >/dev/null 2>/dev/null; then \
+			echo "$(distdir)/$$f is a dummy manpage; cannot create distribution"; \
+			exit 1; \
+		fi; \
+	done
 
-# this is conditioned on ENABLE_MANPAGE_BUILD; it checks for the
-# existence of the file to be installed when building manpages is
-# not enabled.
-install-data-hook: $(ALL_MAN_PAGES)
-if	ENABLE_MANPAGE_BUILD
-	@list="$(man8_pages)"; \
-	for p in $$list; do \
-		pa=$(DESTDIR)$(man8dir)/`echo $$p|sed '$(transform)'`; \
-		echo $(INSTALL) -c -m 644 $$p $(DESTDIR)$(man8dir); \
-		$(INSTALL) -c -m 644 $$p $(DESTDIR)$(man8dir); \
-		echo chown \"$(BINARY_OWNER)\" $$pa;	\
-		chown "$(BINARY_OWNER)" $$pa;		\
-		echo chgrp \"$(SETUID_GROUP)\" $$pa;	\
-		chgrp "$(SETUID_GROUP)" $$pa;		\
-	done
-	@list="$(man5_pages)"; \
-	for p in $$list; do \
-		pa=$(DESTDIR)$(man5dir)/`echo $$p|sed '$(transform)'`; \
-		echo $(INSTALL) -c -m 644 $$p $(DESTDIR)$(man5dir); \
-		$(INSTALL) -c -m 644 $$p $(DESTDIR)$(man5dir); \
-		echo chown \"$(BINARY_OWNER)\" $$pa;	\
-		chown "$(BINARY_OWNER)" $$pa;		\
-		echo chgrp \"$(SETUID_GROUP)\" $$pa;	\
-		chgrp "$(SETUID_GROUP)" $$pa;		\
-	done
-else	!ENABLE_MANPAGE_BUILD
-	@list="$(man8_pages)"; \
-	for p in $$list; do \
-	    if test -e $$p; then \
-		pa=$(DESTDIR)$(man8dir)/`echo $$p|sed '$(transform)'`; \
-		echo $(INSTALL) -c -m 644 $$p $(DESTDIR)$(man8dir); \
-		$(INSTALL) -c -m 644 $$p $(DESTDIR)$(man8dir); \
-		echo chown \"$(BINARY_OWNER)\" $$pa;	\
-		chown "$(BINARY_OWNER)" $$pa;		\
-		echo chgrp \"$(SETUID_GROUP)\" $$pa;	\
-		chgrp "$(SETUID_GROUP)" $$pa;		\
-	    fi \
-	done
-	@list="$(man5_pages)"; \
-	for p in $$list; do \
-	    if test -e $$p; then \
-		pa=$(DESTDIR)$(man5dir)/`echo $$p|sed '$(transform)'`; \
-		echo $(INSTALL) -c -m 644 $$p $(DESTDIR)$(man5dir); \
-		$(INSTALL) -c -m 644 $$p $(DESTDIR)$(man5dir); \
-		echo chown \"$(BINARY_OWNER)\" $$pa;	\
-		chown "$(BINARY_OWNER)" $$pa;		\
-		echo chgrp \"$(SETUID_GROUP)\" $$pa;	\
-		chgrp "$(SETUID_GROUP)" $$pa;		\
-	    fi \
-	done
-endif
+man_MANS = $(WANTED_MAN_PAGES)
